name: E2E on Chrome

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # ou la version de Node.js que tu utilises

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install dependencies with PNPM
        run: pnpm install # Cette étape installe les dépendances

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          project: ./
          browser: chrome
          build: pnpm build
          start: pnpm start
          wait-on: 'http://localhost:3000'
          record: false
          publish-summary: true
          component: false
        env:
          COMMERCE_PROVIDER: ${{ secrets.COMMERCE_PROVIDER }}
          NEXT_PUBLIC_SHOPIFY_STOREFRONT_ACCESS_TOKEN: ${{ secrets.NEXT_PUBLIC_SHOPIFY_STOREFRONT_ACCESS_TOKEN }}
          NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN: ${{ secrets.NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN }}
